### ISSUE TITLE
StorageIntegrationTest.test_end_to_end: Unrecognized SSL message, plaintext connection?

### ISSUE THREAD

**Issue by benjaminran** [BD2KGenomics/dcc-storage#25]
Our forks of dcc-auth (and metadata/storage) removed the specification of the default .p12 keystore used to serve https; instead http is served and a reverse proxy handles ssl termination for all analysis core services. StorageIntegrationTest makes https calls to the auth-server and metadata-server which cause the below error seemingly because the servers are serving http but the test expects https. But the test explicitly depends on dcc-auth version 4.3.2 (whereas our fork would be version r4.3.2). 

It looks like storage-test might be using an unexpected maven artifact (ours instead of icgc's). A quick fix is to add a testing-only config profile to dcc-{auth|metadata|storage}-server that adds the default .p12 keystore, but it would be best to understand why this is happening in the first place.

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.icgc.dcc.storage.test.PartitionedBucketFallbackIntegrationTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.056 sec - in org.icgc.dcc.storage.test.PartitionedBucketFallbackIntegrationTest
Running org.icgc.dcc.storage.test.PartitionedBucketIntegrationTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.052 sec - in org.icgc.dcc.storage.test.PartitionedBucketIntegrationTest
Running org.icgc.dcc.storage.test.StorageIntegrationTest
    ____  ____________   ___         __  __                _____                          
   / __ \/ ____/ ____/  /   | __  __/ /_/ /_              / ___/___  ______   _____  _____
  / / / / /   / /      / /| |/ / / / __/ __ \   ______    \__ \/ _ \/ ___/ | / / _ \/ ___/
 / /_/ / /___/ /___   / ___ / /_/ / /_/ / / /  /_____/   ___/ /  __/ /   | |/ /  __/ /    
/_____/\____/\____/  /_/  |_\__,_/\__/_/ /_/            /____/\___/_/    |___/\___/_/     
                                                                                          
2017-05-22 12:49:48.094  INFO 59839 --- [           main] org.icgc.dcc.auth.server.ServerMain      : Starting ServerMain on eduroam-169-233-216-151.ucsc.edu with PID 59839 (/Users/benjaminran/.m2/repository/org/icgc/dcc/dcc-auth-server/4.3.2/dcc-auth-server-4.3.2.jar started by benjaminran in /Users/benjaminran/dev/dcc/dcc-storage/dcc-storage-test)
2017-05-22 12:49:48.152  INFO 59839 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@51a197d0: startup date [Mon May 22 12:49:48 PDT 2017]; root of context hierarchy
2017-05-22 12:49:48.358  INFO 59840 --- [           main] o.s.boot.SpringApplication               : 
    ____  ____________   __  ___     __            __      __                    _____                          
   / __ \/ ____/ ____/  /  |/  /__  / /_____ _____/ /___ _/ /_____ _            / ___/___  ______   _____  _____
  / / / / /   / /      / /|_/ / _ \/ __/ __ `/ __  / __ `/ __/ __ `/  ______    \__ \/ _ \/ ___/ | / / _ \/ ___/
 / /_/ / /___/ /___   / /  / /  __/ /_/ /_/ / /_/ / /_/ / /_/ /_/ /  /_____/   ___/ /  __/ /   | |/ /  __/ /    
/_____/\____/\____/  /_/  /_/\___/\__/\__,_/\__,_/\__,_/\__/\__,_/            /____/\___/_/    |___/\___/_/     
                                                                                                                
    ____  ____________   _____ __                                          _____                          
   / __ \/ ____/ ____/  / ___// /_____  _________ _____ ____              / ___/___  ______   _____  _____
  / / / / /   / /       \__ \/ __/ __ \/ ___/ __ `/ __ `/ _ \   ______    \__ \/ _ \/ ___/ | / / _ \/ ___/
 / /_/ / /___/ /___    ___/ / /_/ /_/ / /  / /_/ / /_/ /  __/  /_____/   ___/ /  __/ /   | |/ /  __/ /    
/_____/\____/\____/   /____/\__/\____/_/   \__,_/\__, /\___/            /____/\___/_/    |___/\___/_/     
                                                /____/                                                    
2017-05-22 12:49:48.651  INFO 59840 --- [           main] org.icgc.dcc.metadata.server.ServerMain  : Starting ServerMain on eduroam-169-233-216-151.ucsc.edu with PID 59840 (/Users/benjaminran/.m2/repository/org/icgc/dcc/dcc-metadata-server/0.0.22/dcc-metadata-server-0.0.22.jar started by benjaminran in /Users/benjaminran/dev/dcc/dcc-storage/dcc-storage-test)
2017-05-22 12:49:48.652  INFO 59840 --- [           main] org.icgc.dcc.metadata.server.ServerMain  : The following profiles are active: development,secure
2017-05-22 12:49:48.750  INFO 59841 --- [           main] org.icgc.dcc.storage.server.ServerMain   : Starting ServerMain vr1.0.26-SNAPSHOT on eduroam-169-233-216-151.ucsc.edu with PID 59841 (/Users/benjaminran/dev/dcc/dcc-storage/dcc-storage-server/target/dcc-storage-server-r1.0.26-SNAPSHOT.jar started by benjaminran in /Users/benjaminran/dev/dcc/dcc-storage/dcc-storage-test)
2017-05-22 12:49:48.758  INFO 59841 --- [           main] org.icgc.dcc.storage.server.ServerMain   : The following profiles are active: dev,secure,default
2017-05-22 12:49:48.809  INFO 59840 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@3419866c: startup date [Mon May 22 12:49:48 PDT 2017]; root of context hierarchy
2017-05-22 12:49:48.901  INFO 59841 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@5faeada1: startup date [Mon May 22 12:49:48 PDT 2017]; root of context hierarchy
2017-05-22 12:49:49.249  INFO 59839 --- [       Thread-2] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@51a197d0: startup date [Mon May 22 12:49:48 PDT 2017]; root of context hierarchy
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.786 sec <<< FAILURE! - in org.icgc.dcc.storage.test.StorageIntegrationTest
test_end_to_end(org.icgc.dcc.storage.test.StorageIntegrationTest)  Time elapsed: 4.548 sec  <<< ERROR!
javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at sun.security.ssl.InputRecord.handleUnknownRecord(InputRecord.java:710)
	at sun.security.ssl.InputRecord.read(InputRecord.java:527)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1283)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1258)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
	at org.icgc.dcc.storage.test.auth.AuthClient.createAccessToken(AuthClient.java:72)
	at org.icgc.dcc.storage.test.AbstractStorageIntegrationTest.execute(AbstractStorageIntegrationTest.java:136)
	at org.icgc.dcc.storage.test.StorageIntegrationTest.test_end_to_end(StorageIntegrationTest.java:44)

2017-05-22 12:49:49.258  WARN 59839 --- [       Thread-2] ationConfigEmbeddedWebApplicationContext : Exception thrown from ApplicationListener handling ContextClosedEvent
java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@51a197d0: startup date [Mon May 22 12:49:48 PDT 2017]; root of context hierarchy
	at org.springframework.context.support.AbstractApplicationContext.getApplicationEventMulticaster(AbstractApplicationContext.java:344)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:331)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:869)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.doClose(EmbeddedWebApplicationContext.java:150)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:804)
2017-05-22 12:49:49.258  WARN 59839 --- [       Thread-2] ationConfigEmbeddedWebApplicationContext : Exception thrown from LifecycleProcessor on context close
java.lang.IllegalStateException: LifecycleProcessor not initialized - call 'refresh' before invoking lifecycle methods via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@51a197d0: startup date [Mon May 22 12:49:48 PDT 2017]; root of context hierarchy
	at org.springframework.context.support.AbstractApplicationContext.getLifecycleProcessor(AbstractApplicationContext.java:357)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:877)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.doClose(EmbeddedWebApplicationContext.java:150)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:804)

Results :

Tests in error: 
  StorageIntegrationTest.test_end_to_end:44->AbstractStorageIntegrationTest.execute:136 » SSL

Tests run: 3, Failures: 0, Errors: 1, Skipped: 2

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] dcc-storage ........................................ SUCCESS [  1.164 s]
[INFO] dcc-storage-core ................................... SUCCESS [  1.217 s]
[INFO] dcc-storage-fs ..................................... SUCCESS [  0.178 s]
[INFO] dcc-storage-client ................................. SUCCESS [ 10.496 s]
[INFO] dcc-storage-server ................................. SUCCESS [ 11.905 s]
[INFO] dcc-storage-test ................................... FAILURE [  6.097 s]
[INFO] icgc-storage-client ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 31.384 s
[INFO] Finished at: 2017-05-22T12:49:49-07:00
[INFO] Final Memory: 52M/528M
[INFO] ------------------------------------------------------------------------
```

**Comment by benjaminran** [comment]
This was a false alarm; I had left a dockerized version of the current auth server running with localhost:8443 forwarded to the docker auth server and the test wasn't outputting a warning that its auth-server wasn't started on port 8443 as expected. The docker container was serving http--hence the error message.
